name: Run Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Streamlit app
        run: |
          streamlit run app.py
          if [ $? -eq 0 ]; then
            echo "Streamlit app executed successfully"
          else
            echo "Error: Streamlit app execution failed"
            exit 1  # Terminate the workflow due to the failure
          fi
